### ISSUE TITLE
GET WFS Data

### ISSUE THREAD

**Issue by asonnenschein** [ngds/data-archiver#10]
Write a handler that does something like this:

-Figure out if a URL is for a WFS
-Maybe have a look at the getCapabilities doc
-Stream the data as GML to an output text file

@smrazgs Do we only need to support OGC or should we handle ArcGIS services as well?  Also, should we do anything with WMS data?

**Comment by smrgeoinfo** [comment]
Lets start with OGC; our information exchanges specify OGC services.  If the software can be constructed so that connectors for other data services could be inserted that would be a good thing.

If the resource is only accessible as a WMS, there's not much we can do to archive it--we can't actually get the data.  Hopefully there will be an associated dataset or image file if its just an image WMS.
